export const CHANGE_SEARCH_TARGET = "CHANGE_SEARCH_TARGET";
export const CHANGE_BOUNDARIES = "CHANGE_BOUNDARIES";
export const UPDATE_RECIPES = "UPDATE_RECIPES";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const DISABLE_NEXT = "DISABLE_NEXT";
export const POPULATE_RESULT = "POPULATE_RESULT";
export const RESET_STATE = "RESET_STATE";